// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oncogenes.DAL;

#nullable disable

namespace Oncogenes.DAL.Migrations
{
    [DbContext(typeof(OncogenesContext))]
    [Migration("20230528180942_fix")]
    partial class fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ActivationDrug", b =>
                {
                    b.Property<int>("ActivationsActivationId")
                        .HasColumnType("int");

                    b.Property<int>("DrugsDrugId")
                        .HasColumnType("int");

                    b.HasKey("ActivationsActivationId", "DrugsDrugId");

                    b.HasIndex("DrugsDrugId");

                    b.ToTable("ActivationDrug");
                });

            modelBuilder.Entity("DiseaseDiseaseCodes", b =>
                {
                    b.Property<int>("DiseaseCodeId")
                        .HasColumnType("int");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.HasKey("DiseaseCodeId", "DiseaseId");

                    b.HasIndex("DiseaseId");

                    b.ToTable("DiseaseDiseaseCodes");
                });

            modelBuilder.Entity("DiseaseGene", b =>
                {
                    b.Property<int>("DiseasesDiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("OncogenesId")
                        .HasColumnType("int");

                    b.HasKey("DiseasesDiseaseId", "OncogenesId");

                    b.HasIndex("OncogenesId");

                    b.ToTable("DiseaseGene");
                });

            modelBuilder.Entity("DiseaseMedicalTest", b =>
                {
                    b.Property<int>("DiseasesDiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalTestsMedicalTestId")
                        .HasColumnType("int");

                    b.HasKey("DiseasesDiseaseId", "MedicalTestsMedicalTestId");

                    b.HasIndex("MedicalTestsMedicalTestId");

                    b.ToTable("DiseaseMedicalTest");
                });

            modelBuilder.Entity("DiseaseTreatment", b =>
                {
                    b.Property<int>("DiseasesDiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentsTreatmentId")
                        .HasColumnType("int");

                    b.HasKey("DiseasesDiseaseId", "TreatmentsTreatmentId");

                    b.HasIndex("TreatmentsTreatmentId");

                    b.ToTable("DiseaseTreatment");
                });

            modelBuilder.Entity("DrugGene", b =>
                {
                    b.Property<int>("DrugsDrugId")
                        .HasColumnType("int");

                    b.Property<int>("OncogenesId")
                        .HasColumnType("int");

                    b.HasKey("DrugsDrugId", "OncogenesId");

                    b.HasIndex("OncogenesId");

                    b.ToTable("DrugGene");
                });

            modelBuilder.Entity("Oncogenes.Domain.Activation", b =>
                {
                    b.Property<int>("ActivationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActionabilityRank")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CompletionStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ControlNumber")
                        .HasColumnType("int");

                    b.Property<string>("ControlTreatment")
                        .HasColumnType("longtext");

                    b.Property<int>("DevelopmentStatus")
                        .HasColumnType("int");

                    b.Property<int?>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MutationRemark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("NumberOfPatients")
                        .HasColumnType("int");

                    b.Property<int>("OncogeneId")
                        .HasColumnType("int");

                    b.Property<string>("TestingRequired")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TreatedNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TrialPrimaryCompletionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TrialStatus")
                        .HasColumnType("int");

                    b.HasKey("ActivationId");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("OncogeneId");

                    b.ToTable("Activations");
                });

            modelBuilder.Entity("Oncogenes.Domain.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DiseaseId");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("Oncogenes.Domain.DiseaseCode", b =>
                {
                    b.Property<int>("DiseaseCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodeDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("CodeType")
                        .HasColumnType("int");

                    b.Property<string>("DiseaseClassificator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DiseaseCodeId");

                    b.ToTable("DiseaseCodes");
                });

            modelBuilder.Entity("Oncogenes.Domain.Drug", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GenericDrugName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DrugId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("Oncogenes.Domain.Gene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CancerSyndrome")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TumorTypes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Oncogenes");
                });

            modelBuilder.Entity("Oncogenes.Domain.MedicalTest", b =>
                {
                    b.Property<int>("MedicalTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.HasKey("MedicalTestId");

                    b.ToTable("MedicalTests");
                });

            modelBuilder.Entity("Oncogenes.Domain.Treatment", b =>
                {
                    b.Property<int>("TreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.HasKey("TreatmentId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("ActivationDrug", b =>
                {
                    b.HasOne("Oncogenes.Domain.Activation", null)
                        .WithMany()
                        .HasForeignKey("ActivationsActivationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oncogenes.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugsDrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiseaseDiseaseCodes", b =>
                {
                    b.HasOne("Oncogenes.Domain.DiseaseCode", null)
                        .WithMany()
                        .HasForeignKey("DiseaseCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oncogenes.Domain.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiseaseGene", b =>
                {
                    b.HasOne("Oncogenes.Domain.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseasesDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oncogenes.Domain.Gene", null)
                        .WithMany()
                        .HasForeignKey("OncogenesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiseaseMedicalTest", b =>
                {
                    b.HasOne("Oncogenes.Domain.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseasesDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oncogenes.Domain.MedicalTest", null)
                        .WithMany()
                        .HasForeignKey("MedicalTestsMedicalTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiseaseTreatment", b =>
                {
                    b.HasOne("Oncogenes.Domain.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseasesDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oncogenes.Domain.Treatment", null)
                        .WithMany()
                        .HasForeignKey("TreatmentsTreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DrugGene", b =>
                {
                    b.HasOne("Oncogenes.Domain.Drug", null)
                        .WithMany()
                        .HasForeignKey("DrugsDrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oncogenes.Domain.Gene", null)
                        .WithMany()
                        .HasForeignKey("OncogenesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oncogenes.Domain.Activation", b =>
                {
                    b.HasOne("Oncogenes.Domain.Disease", null)
                        .WithMany("Activations")
                        .HasForeignKey("DiseaseId");

                    b.HasOne("Oncogenes.Domain.Gene", "Oncogene")
                        .WithMany("Activations")
                        .HasForeignKey("OncogeneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oncogene");
                });

            modelBuilder.Entity("Oncogenes.Domain.Disease", b =>
                {
                    b.Navigation("Activations");
                });

            modelBuilder.Entity("Oncogenes.Domain.Gene", b =>
                {
                    b.Navigation("Activations");
                });
#pragma warning restore 612, 618
        }
    }
}
